apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: home-media
  labels:
    main: hm-app
    app: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      main: hm-app
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        main: hm-app
        app: {{ .Release.Name }}-app
    spec:
      # nodeSelector:
      #   {{ if eq .Release.Name "jellyfin" }}workload: "gpu"
      #   {{ end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.container.image }}
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Asia/Yerevan"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - name: {{ .Release.Name }}-web
          containerPort: {{ .Values.container.port }}
        volumeMounts:
        - name: hm-volume
          mountPath: ./data/downloads
          subPath: ./data_my/Downloads
        - name: hm-volume
          mountPath: ./config
          subPath: ./data_my/home-media/{{ .Release.Name }}/config
        resources:
          requests:
            memory: 500Mi
            cpu: 256m
          limits:
            memory: 500Mi
            cpu: 500m
      volumes:
      - name: hm-volume
        persistentVolumeClaim:
          claimName: hm-claim