{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-creds
  namespace: home-media
  annotations:
    avp.kubernetes.io/path: "kv/data/home-media/postgres"
type: Opaque
stringData:
  user: <user>
  password: <password>
  host: <host>
  port: <port>
{{- end }}
