apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: home-media
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
  - name: {{ .Release.Name }}-web
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
