apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: avp-secret-reader
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts"]
    verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: avp-secret-reader
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: argocd
roleRef:
  kind: Role
  name: avp-secret-reader
  apiGroup: rbac.authorization.k8s.io
