apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kapowarr
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: home_lab/defaults/helm_media
    repoURL: https://github.com/D1NaR1us/k8s_home_lab.git
    targetRevision: HEAD
    helm:
      values: |
        container:
          image: mrcas/kapowarr:latest
          port: 5656
          targetPort: 5656
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
