apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: notes
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: home-media
  source:
    path: home_lab/defaults/helm_media
    repoURL: https://github.com/D1NaR1us/k8s_home_lab.git
    targetRevision: HEAD
    helm:
      values: |
        container:
          image: ghcr.io/gamosoft/notediscovery:latest
          port: 8000
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: notes-postgres-creds
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: notes-postgres-creds
                key: password
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: notes-postgres-creds
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: notes-postgres-creds
                key: port
          - name: POSTGRES_DB
            value: "notediscovery_db"
          extraVolumeMounts:
            - name: hm-volume
              mountPath: /app/data
              subPath: Obsidian/Work_Notes
        postgres:
          enabled: true
          targetPorts: 8000
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
