apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: notes
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: home-media
  source:
    path: home_lab/defaults/helm_media
    repoURL: https://github.com/D1NaR1us/k8s_home_lab.git
    targetRevision: HEAD
    helm:
      values: |
        container:
          image: triliumnext/trilium:latest
          port: 8080
          extraVolumeMounts:
            - name: hm-volume
              mountPath: /home/node/trilium-data
              subPath: Obsidian/Work_Notes
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
