apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: notes
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: home-media
  source:
    path: home_lab/defaults/helm_media
    repoURL: https://github.com/D1NaR1us/k8s_home_lab.git
    targetRevision: HEAD
    helm:
      values: |
        container:
          image: ghcr.io/silverbulletmd/silverbullet:latest
          port: 3000
          extraVolumeMounts:
            - name: hm-volume
              mountPath: /space
              subPath: /Obsidian/Work_Notes
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
