apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: my-notes
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: home-media
  source:
    path: home_lab/defaults/helm_media
    repoURL: https://github.com/D1NaR1us/k8s_home_lab.git
    targetRevision: HEAD
    helm:
      values: |
        container:
          image: battermanz/hatchdoor:latest
          port: 42824
          env:
          - name: HOST
            value: "127.0.0.1"
          extraVolumeMounts:
            - name: hm-volume
              mountPath: /app/data/Alice-personal
              subPath: Agents/obsidian/Alice-personal
            - name: hm-volume
              mountPath: /app/data/skills
              subPath: Agents/shared/skills
            - name: hm-volume
              mountPath: /data/attachments-inbox
              subPath: data_my/home-media/my-notes/attachments-inbox
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
