apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: pv-secret
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: defaults/home-media_pv_secret
    repoURL: https://github.com/D1NaR1us/helm_home-media
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
