apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: sonarr
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: home_lab/defaults/helm_media
    repoURL: https://github.com/D1NaR1us/k8s_home_lab.git
    targetRevision: HEAD
    helm:
      values: |
        container:
          image: linuxserver/sonarr:latest
          port: 8989
          targetPort: 8989
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


# if you have postgres DB, you may add these part of configuration into config.xml. It will avoid some DB lock issue in a future
# <PostgresUser>postgres</PostgresUser>
# <PostgresPassword><TYPE_HERE_YOUR_PASS></PostgresPassword>
# <PostgresPort>5432</PostgresPort>
# <PostgresHost><TYPE_HERE_IP_ADDR></PostgresHost>
# <AnalyticsEnabled>False</AnalyticsEnabled>
# <UpdateAutomatically>True</UpdateAutomatically>