apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: torrent
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: defaults/helm_media
    repoURL: https://github.com/D1NaR1us/helm_home-media
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
