apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
  namespace: vault
type: Opaque
stringData:
  key1: s.VAULT_UNSEAL_KEY_1
  key2: s.VAULT_UNSEAL_KEY_2
  key3: s.VAULT_UNSEAL_KEY_3
  root: s.VAULT_UNSEAL_ROOT_TOKEN
