apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-secrets
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: ai-apps
  source:
    path: ai_lab/defaults/custom_secrets
    repoURL: https://github.com/D1NaR1us/k8s_home_lab.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
