apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-pv-secret
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: ai_lab/defaults/ai_pv_secret
    repoURL: https://github.com/D1NaR1us/k8s_home_lab.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
