apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: main-home-media
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argocd_apps/apps
    repoURL: https://github.com/D1NaR1us/helm_home-media
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
