apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: main-home-media
  namespace: argocd
spec: 
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: home_lab/argocd_apps/apps
    repoURL: https://github.com/D1NaR1us/k8s_home_lab
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
