apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-unseal
  namespace: vault
spec:
  schedule: "*/2 * * * *"   # каждые 2 минуты
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: unseal
              image: hashicorp/vault:1.15
              env:
                - name: VAULT_ADDR
                  value: http://vault.vault.svc.cluster.local:8200
              command:
                - /bin/sh
                - -c
                - |
                  if vault status | grep -q "Sealed.*true"; then
                    echo "Vault sealed → unsealing"
                    vault operator unseal $(cat /keys/key1)
                    vault operator unseal $(cat /keys/key2)
                    vault operator unseal $(cat /keys/key3)
                  else
                    echo "Vault already unsealed"
                  fi
              volumeMounts:
                - name: keys
                  mountPath: /keys
          volumes:
            - name: keys
              secret:
                secretName: vault-unseal
