apiVersion: v1
kind: Secret
metadata:
  name: n8n-postgres-creds
  namespace: ai-apps
  annotations:
    avp.kubernetes.io/path: "kv/data/ai-apps/postgres"
type: Opaque
stringData:
  user: <user>
  password: <password>
  host: <host>
  port: <port>
  database: <database>
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-tokens
  namespace: ai-apps
  annotations:
    avp.kubernetes.io/path: "kv/data/ai-apps/n8n-tokens"
type: Opaque
stringData:
  OPENAI_API_KEY: <OPENAI_API_KEY>
  N8N_ENCRYPTION_KEY: <N8N_ENCRYPTION_KEY>
