apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    main: ai-app
    app: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      main: ai-app
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        main: ai-app
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.container.image }}
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Europe/Sofia"
        {{- if .Values.container.env }}
        {{- toYaml .Values.container.env | nindent 8 }}
        {{- end }}
        {{- if .Values.postgres.enabled }}
        {{- range $name, $key := .Values.postgres.env }}
        - name: {{ $name }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}-postgres-creds
              key: {{ $key }}
        {{- end }}
        {{- end }}
        {{- if .Values.tokens.enabled }}
        {{- range .Values.tokens.keys }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}-tokens
              key: {{ . }}
        {{- end }}
        {{- end }}
        ports:
        - name: {{ .Release.Name }}-web
          containerPort: {{ .Values.container.port }}
        {{- if .Values.container.extraVolumeMounts }}
        volumeMounts:
        {{- range .Values.container.extraVolumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- else if eq .name $.Values.volumeClaimName }}
          subPath: data_my/ai-apps/{{ $.Release.Name }}
          {{- end }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.container.resources | nindent 10 }}
      volumes:
      - name: {{ .Values.volumeClaimName }}
        persistentVolumeClaim:
          claimName: {{ .Values.volumeClaimName }}
