{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-creds
  namespace: {{ .Values.namespace }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.postgres.avpPath }}"
type: Opaque
stringData:
  user: <user>
  password: <password>
  host: <host>
  port: <port>
  database: <database>
{{- end }}
