{{- if .Values.tokens.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tokens
  namespace: {{ .Values.namespace }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.tokens.avpPath }}"
type: Opaque
stringData:
  {{- range .Values.tokens.keys }}
  {{ . }}: <{{ . }}>
  {{- end }}
{{- end }}
