apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hm-claim
  namespace: home-media
spec:
  volumeName: hm-nfs
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

--- 

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: hm-nfs
  namespace: home-media
spec: 
  accessModes: 
    - ReadWriteMany
  capacity: 
    storage: 500Gi
  nfs: 
    path: "/mnt/home-media"
    server: 192.168.50.3
  storageClassName: nfs
