apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: linuxserver/prowlarr:latest
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 9696
- target:
    kind: Service
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 9696
    - op: replace
      path: /spec/ports/0/targetPort
      value: 9696
    