apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
data:
  server.secretkey: "<Secret_Key>"
  admin.password: "<ARGO_PWD_ENCRYPTED>"
  admin.passwordMtime: "<PASSWORD_dMtime>"