apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unsealer
  namespace: vault

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-unsealer-role
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unsealer-binding
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault-unsealer
    namespace: vault
roleRef:
  kind: Role
  name: vault-unsealer-role
  apiGroup: rbac.authorization.k8s.io
