apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal
  namespace: vault
type: Opaque
stringData:
  key1: VAULT_UNSEAL_KEY_1
  key2: VAULT_UNSEAL_KEY_2
  key3: VAULT_UNSEAL_KEY_3
  root_token: VAULT_UNSEAL_ROOT_KEY
